name: PHPUnit

permissions:
  pull-requests: write

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    name: "Build & run PHPUnit"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup docker
        uses: docker/setup-buildx-action@v3
      - name: Build image
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: phalcon-project-tester:latest
          context: .
          file: ./docker/Dockerfile
          target: core
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true
      - name: Start test runner container
        run: |-
          docker container run --name test-runner --rm -v ".:/var/www/app/" -e "DEV_UID=$(id -u)" phalcon-project-tester:latest \
          php /var/www/app/vendor/bin/phpunit --show-uncovered-for-coverage-text --coverage-text=/var/www/app/coverage.txt

      - name: 'Add Code Coverage to Job Summary'
        run: |
          touch code-coverage-summary.md
          echo "## Code Coverage" >> code-coverage-summary.md
          echo >> code-coverage-summary.md
          cat coverage.txt | ./.github/scripts/parse_coverage.sh | tee -a code-coverage-summary.md
          echo >> code-coverage-summary.md
          cat code-coverage-summary.md >> $GITHUB_STEP_SUMMARY

      - name: 'Add Code Coverage Summary as PR Comment'
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-summary.md